### ISSUE TITLE
Is there any way to automatize more than games?

### ISSUE THREAD

**Issue by Prozoon700** [Diskcraft/diskcraft#37]
Hi.
I would like to know if is there any way to automatize the hosting of web servers, domains, etc...
It's needed to do it manually? It's possible but coding?

Thanks.

**Comment by PenguCCN** [comment]
Currently no, DiskCraft doesn't have any implementation for web servers, domains, ect.

Someone would have to contribute the code in a pull request.

**Comment by Prozoon700** [comment]
Okay, thanks
